### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mystycs** [nhsengland/ckanext-adfs#5]
I have this installed in a docker container using the instructions given on ckans documentation

I went ahead and installed the extension as so below:

```
docker exec -it ckan /bin/bash -c "export TERM=xterm; exec bash"
source $CKAN_VENV/bin/activate && cd $CKAN_VENV/src/

git clone https://github.com/nhsengland/ckanext-adfs.git
cd ckanext-adfs
pip install -r requirements.txt
python setup.py install
python setup.py develop
cd ..

```

Then i added ckan.plugins = adfs to my production.ini and added adfs_wtrealm  and adfs_metadata_url 

Now when i restart ckan i get Internal Server Error when loading up the page and the error log below.

Looks like something about session not being registered?

> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
> ckan          |     response = self.full_dispatch_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
> ckan          |     rv = self.handle_user_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
> ckan          |     reraise(exc_type, exc_value, tb)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
> ckan          |     rv = self.preprocess_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
> ckan          |     rv = func()
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 281, in ckan_before_request
> ckan          |     identify_user()
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/views/__init__.py", line 100, in identify_user
> ckan          |     item.identify()
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-adfs/ckanext/adfs/plugin.py", line 85, in identify
> ckan          |     user = pylons.session.get('adfs-user')
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
> ckan          |     return getattr(self._current_obj(), attr)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
> ckan          |     'thread' % self.____name__)
> ckan          | TypeError: No object (name: session) has been registered for this thread
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
> ckan          |     self.finish_request(request, client_address)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
> ckan          |     self.RequestHandlerClass(request, client_address, self)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
> ckan          |     self.handle()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
> ckan          |     BaseHTTPRequestHandler.handle(self)
> ckan          |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
> ckan          |     self.handle_one_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
> ckan          |     self.wsgi_execute()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
> ckan          |     self.wsgi_start_response)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
> ckan          |     return self.apps[app_name](environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
> ckan          |     app_iter = app(environ, wrapper.wrap_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
> ckan          |     return request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
> ckan          |     response = request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
> ckan          |     return self.wsgi_app(environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
> ckan          |     return self.wrap_app(environ, session_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
> ckan          |     response = self.handle_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
> ckan          |     return self.finalize_request(handler(e), from_error_handler=True)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 411, in error_handler
> ckan          |     extra_vars = {u'code': e.code, u'content': e.description}
> ckan          | AttributeError: 'exceptions.TypeError' object has no attribute 'code'
> ckan          | [2018-06-25 19:30:43,302] ERROR in app: Exception on / [GET]
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
> ckan          |     response = self.full_dispatch_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
> ckan          |     rv = self.handle_user_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
> ckan          |     reraise(exc_type, exc_value, tb)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
> ckan          |     rv = self.preprocess_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
> ckan          |     rv = func()
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 281, in ckan_before_request
> ckan          |     identify_user()
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/views/__init__.py", line 100, in identify_user
> ckan          |     item.identify()
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-adfs/ckanext/adfs/plugin.py", line 85, in identify
> ckan          |     user = pylons.session.get('adfs-user')
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
> ckan          |     return getattr(self._current_obj(), attr)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
> ckan          |     'thread' % self.____name__)
> ckan          | TypeError: No object (name: session) has been registered for this thread
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
> ckan          |     self.finish_request(request, client_address)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
> ckan          |     self.RequestHandlerClass(request, client_address, self)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
> ckan          |     self.handle()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
> ckan          |     BaseHTTPRequestHandler.handle(self)
> ckan          |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
> ckan          |     self.handle_one_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
> ckan          |     self.wsgi_execute()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
> ckan          |     self.wsgi_start_response)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
> ckan          |     return self.apps[app_name](environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
> ckan          |     app_iter = app(environ, wrapper.wrap_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
> ckan          |     return request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
> ckan          |     response = request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
> ckan          |     return self.wsgi_app(environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
> ckan          |     return self.wrap_app(environ, session_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
> ckan          |     response = self.handle_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
> ckan          |     return self.finalize_request(handler(e), from_error_handler=True)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 411, in error_handler
> ckan          |     extra_vars = {u'code': e.code, u'content': e.description}
> ckan          | AttributeError: 'exceptions.TypeError' object has no attribute 'code'
> ckan          | Initialising DB: SUCCESS
> ckan          | 2018-06-25 19:36:22,069 INFO  [ckan.config.environment] Loading static files from public
> ckan          | 2018-06-25 19:36:22,090 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
> ckan          | 2018-06-25 19:36:22,723 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
> ckan          | [2018-06-25 19:36:24,188] ERROR in app: Exception on / [GET]
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
> ckan          |     response = self.full_dispatch_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
> ckan          |     rv = self.handle_user_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
> ckan          |     reraise(exc_type, exc_value, tb)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
> ckan          |     rv = self.preprocess_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
> ckan          |     rv = func()
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 281, in ckan_before_request
> ckan          |     identify_user()
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/views/__init__.py", line 100, in identify_user
> ckan          |     item.identify()
> ckan          |   File "/usr/lib/ckan/venv/src/ckanext-adfs/ckanext/adfs/plugin.py", line 85, in identify
> ckan          |     user = pylons.session.get('adfs-user')
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
> ckan          |     return getattr(self._current_obj(), attr)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
> ckan          |     'thread' % self.____name__)
> ckan          | TypeError: No object (name: session) has been registered for this thread
> ckan          | Traceback (most recent call last):
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
> ckan          |     self.finish_request(request, client_address)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
> ckan          |     self.RequestHandlerClass(request, client_address, self)
> ckan          |   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
> ckan          |     self.handle()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
> ckan          |     BaseHTTPRequestHandler.handle(self)
> ckan          |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
> ckan          |     self.handle_one_request()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
> ckan          |     self.wsgi_execute()
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
> ckan          |     self.wsgi_start_response)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
> ckan          |     return self.apps[app_name](environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
> ckan          |     app_iter = app(environ, wrapper.wrap_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
> ckan          |     return request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
> ckan          |     resp = self.call_func(req, *args, **self.kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
> ckan          |     return self.func(req, *args, **kwargs)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
> ckan          |     response = request.get_response(self.app)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
> ckan          |     application, catch_exc_info=False)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
> ckan          |     app_iter = application(self.environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
> ckan          |     return self.wsgi_app(environ, start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
> ckan          |     return self.wrap_app(environ, session_start_response)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
> ckan          |     response = self.handle_exception(e)
> ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
> ckan          |     return self.finalize_request(handler(e), from_error_handler=True)
> ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 411, in error_handler
> ckan          |     extra_vars = {u'code': e.code, u'content': e.description}
> ckan          | AttributeError: 'exceptions.TypeError' object has no attribute 'code'
>

**Comment by boykoc** [comment]
I didn't get this error but did you install the required packages?

`sudo apt-get install libxml2 libxml2-dev libxslt1.1 libxslt1-dev openssl libssl-dev swig python-dev`

**Comment by mystycs** [comment]
Yeah and im running on 2.8.0 using a docker image. How about you?

I read about pylons moving over to flask. Could it be possible that it is an issue with pylons.session not working anymore in 2.8.0?

**Comment by boykoc** [comment]
I'm running a 2.7 source install on ubuntu server.  I'll try to build 2.8 and test.

**Comment by mystycs** [comment]
Much appreciated! Let me know what you find.

Thanks!

**Comment by boykoc** [comment]
I created a fresh CKAN 2.8 install from source on Ubuntu 16 and get the same error as you. However, using 2.7.3 it works fine.

I've tried a few things and been looking over the docs to see what change happened that caused this and I can't find an exact one yet but I'm thinking you're right it has to do with the [move from pylons to flask](https://github.com/ckan/ckan/wiki/Migration-from-Pylons-to-Flask#flask-views-blueprints-and-routing) (aslo [see this](http://docs.ckan.org/en/2.8/extensions/flask-migration.html)).  I'm going to try and troubleshoot it some more when I have time. I'll need to upgrade soon anyway.  

I did try removing sessions but received different errors. The error above actually has another one in it as well which kept coming up. Also, based on this [section of the docs](https://github.com/ckan/ckan/wiki/Migration-from-Pylons-to-Flask#sessions) I'm thinking sessions should still be working. I'm going to try flipping out the `IRoutes` Interface for the updated version and see how that goes.

I'll post back as I find out more.

**Comment by mystycs** [comment]
I was actually able to get it working for 2.8 using the same exact method you did. all I did was switch from pylons sessions to flask sessions and made a small update in ckans views init.py file. 

Although then pylonsconfig started not working so I had to hard-code the variables. 

I'll share my updates here shortly.

Do let me know what you find though!

**Comment by mystycs** [comment]
So funny story i had to edit the `views/__init__.py` file and change line 101 to

```
               try:
                if g.user:
                    break
            except AttributeError:
                continue
```

But now if i login which now works, on every computer i visit my ckan site on it is logged in as me. Its the weirdest thing. Basically i log in on computer 1, computer 2 3 4 5 6 etcc... will be logged in as me even if they never logged in

Mind you i replaced the plugins.py session and request with flasks version.
Is there something wrong with the session going on in the background?

**Comment by boykoc** [comment]
@mystycs I have not experienced or fully tested for your second / most recent issue (logging in on multiple computers). But for your first issue I finally had time to dig into it. Essentially had to set c.user to None in identify() and stop using pylons directly for things like sessions. You can see these commits if your interested. More details are in my commit messages as well.

- [Task: Switch to common flask/pylons objects and methods.](https://github.com/boykoc/ckanext-adfs/commit/d1c23d042eb522127112d5cc55c3da527b770da9)
- [Task: Set c.user to None.](https://github.com/boykoc/ckanext-adfs/commit/b2ced38f0e2465e1ad29a69078e9dfd1aefc904c)
